### PR TITLE
LPS-78678 Fix up language keys in the web module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78678](https://issues.liferay.com/browse/LPS-78678).<br><br>Hey Dennis, let me know if there's anything else you think needs to change<br><br>/cc @pei-jung @willnewbury

### CODE REVIEW

**Comment by dejuknow** [comment]
@drewbrokke, see the following

all-ambiguous-data-was-forgotten: remove? not being used anymore?
data-to-export: can be removed after finishing LPS-79667
personal-site-was-successfully-forgotten: let's change "forgotten" to "deleted"

**Comment by drewbrokke** [comment]
- [x] all-ambiguous-data-was-forgotten: remove? not being used anymore? (it's in use [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/user-associated-data/user-associated-data-web/src/main/resources/META-INF/resources/view_uad_summary.jsp#L125))
- [ ] data-to-export: can be removed after finishing LPS-79667
- [ ] personal-site-was-successfully-forgotten: let's change "forgotten" to "deleted"

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/57215.

**Comment by pei-jung** [comment]
Yes, I will remove the `data-to-export` key when I work on LPS-79667

**Comment by drewbrokke** [comment]
Thanks @pei-jung!

**Comment by drewbrokke** [comment]
@dejuknow that makes sense

- [ ] all-ambiguous-data-was-forgotten -> Application data successfully reviewed.
- [ ] all-data-was-anonymized -> Remaining data successfully anonymized.
- [ ] personal-site-was-successfully-forgotten -> Personal site successfully deleted.
- [ ] user-was-successfully-deactivated -> User successfully deactivated.

**Pull request closed without merging**
