### PR TITLE
SYNC-1750

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by dejuknow** [comment]
Can you apply this same logic to UserGroupRoleModelListener?

https://github.com/dejuknow/liferay-portal/blob/master/modules/apps/sync/sync-service/src/main/java/com/liferay/sync/internal/model/listener/UserGroupRoleModelListener.java

**Comment by mbowerman** [comment]
Resent at https://github.com/dejuknow/liferay-portal/pull/104.

**Comment by dejuknow** [comment]
View total diff: https://github.com/dejuknow/liferay-portal/compare/3fd1caa277...b15bb2aace

**Pull request closed without merging**
